### ISSUE TITLE
[BUG]: An error while running fcs_gx clean genome on the FCS adapter result report (fcs_adaptor_report.txt)

### ISSUE THREAD

**Issue by maruiqi0710** [ncbi/fcs#104]
When following the instructions at https://github.com/ncbi/fcs/wiki/FCS-adaptor-quickstart#clean-the-genome, I encountered an error while running the command fcs_gx clean genome on the FCS adapter result report (fcs_adaptor_report.txt). The command I used is as follows:

> conda activate singularity
> export FCS_DEFAULT_IMAGE="/XX/fcs-gx.sif"
> 
> cat $input_fasta | \
>   python3 $fcs_gx clean genome \
>   --action-report ./outputdir/fcs_adaptor_report.txt \
>   --output $output_fasta \
>   --contam-fasta-out $output_contam_fasta

  
Here is the content of fcs_adaptor_report.txt:

> #accession	length	action	range	name
> scaffold_12	97067	ACTION_TRIM	97047..97067	CONTAMINATION_SOURCE_TYPE_ADAPTOR:NGB00843.1:Epicentre Biotechnologies Nextera DNA Sample Prep Kit Transposon Sequence (Oligonucleotide sequence copyright 2007-2012 Illumina, Inc. All rights reserved.); CONTAMINATION_SOURCE_TYPE_ADAPTOR:NGB04007.1:Illumina TruSeq Synthetic Long-Read DNA Adapter
> scaffold_14	36639	ACTION_TRIM	36603..36639	CONTAMINATION_SOURCE_TYPE_ADAPTOR:NGB00726.1:Illumina Nextera transposase sequence Read 2 (Oligonucleotide sequence copyright 2007-2012 Illumina, Inc. All rights reserved.)
> scaffold_2	1466650	ACTION_TRIM	1..19	CONTAMINATION_SOURCE_TYPE_ADAPTOR:NGB04007.1:Illumina TruSeq Synthetic Long-Read DNA Adapter
> scaffold_3	1295407	ACTION_TRIM	1..20,1295388..1295407	CONTAMINATION_SOURCE_TYPE_ADAPTOR:NGB04007.1:Illumina TruSeq Synthetic Long-Read DNA Adapter; CONTAMINATION_SOURCE_TYPE_ADAPTOR:NGB00843.1:Epicentre Biotechnologies Nextera DNA Sample Prep Kit Transposon Sequence (Oligonucleotide sequence copyright 2007-2012 Illumina, Inc. All rights reserved.)
> scaffold_6	968238	ACTION_TRIM	1..29	CONTAMINATION_SOURCE_TYPE_ADAPTOR:NGB04007.1:Illumina TruSeq Synthetic Long-Read DNA Adapter

The contents of the log file are as follows:

> NCBI collects limited usage data for each run of FCS by default. To disable usage reporting:
> 
> python3 fcs.py --no-report-analytics ...
> 
> or export NCBI_FCS_REPORT_ANALYTICS=1 to enable,
> or export NCBI_FCS_REPORT_ANALYTICS=0 to disable the reporting.
> 
> Usage data collected by NCBI is documented in the FCS privacy notice
> at https://github.com/ncbi/fcs/blob/main/PRIVACY.md
> 
> --------------------------------------------------------------------------------------------
> INFO:    Converting SIF file to temporary sandbox...
> Fatal error: map::at
> INFO:    Cleaning up image...
> Traceback (most recent call last):
>   File "/Software/Bioinfo_Software/fcs-0.5.4/dist/fcs.py", line 476, in <module>
>     sys.exit(main())
>   File "/Software/Bioinfo_Software/fcs-0.5.4/dist/fcs.py", line 465, in main
>     gx.run()
>   File "/Software/Bioinfo_Software/fcs-0.5.4/dist/fcs.py", line 347, in run
>     self.args.func(self)
>   File "/Software/Bioinfo_Software/fcs-0.5.4/dist/fcs.py", line 343, in run_clean_mode
>     self.run_gx()
>   File "/Software/Bioinfo_Software/fcs-0.5.4/dist/fcs.py", line 243, in run_gx
>     self.safe_exec(docker_args)
>   File "/Software/Bioinfo_Software/fcs-0.5.4/dist/fcs.py", line 168, in safe_exec
>     subprocess.run(args, shell=False, check=True, text=True, stdout=sys.stdout, stderr=sys.stderr)
>   File "/usr/lib/python3.10/subprocess.py", line 524, in run
>     raise CalledProcessError(retcode, process.args,
> subprocess.CalledProcessError: Command '['singularity', 'exec', '--bind', '/media/XXX:/report-volume/', '--bind', '/media/XXX:/output-volume/', '--bind', '/media/XXX:/contam-out-volume/', '/home/Software_Database/fcs_gx/Singularity/fcs-gx.sif', '/app/bin/gx', 'clean-genome', '--action-report', '/report-volume/fcs_adaptor_report.txt', '--output', '/output-volume/XXX.fna', '--contam-fasta-out', '/contam-out-volume/XXX.fna']' returned non-zero exit status 1.
>

**Comment by maruiqi0710** [comment]
The issue has been resolved

**Comment by ereboud** [comment]
I have the same issue. Do you know what was causing the problem?

**Comment by maruiqi0710** [comment]
> I have the same issue. Do you know what was causing the problem?

Step 1:
	fcsadaptor \
	--fasta-input $original_fasta_file \
	--output-dir $fcsadaptor_out_dir \
	--euk \
	--container-engine singularity \
	--image $singularity_image

Step 2:
  cat $original_fasta_file | \
  python3 $fcs_gx clean genome \
  --action-report $fcsadaptor_report.txt \
  --output $fcsadaptor_output_fasta \
  --contam-fasta-out $fcsadaptor_output_contam_fasta

Step3:
  python3 $fcs_gx \
  --env-file $env_file \
  screen genome \
  --fasta $fcsadaptor_output_fasta \
  --tax-id tax-id \
  --gx-db $GXDB_LOC \
  --allow-same-species True \
  --out-dir $fcs_gx_out_dir \
  --save-hits True \
  --generate-logfile True

Step4:
  cat $fcsadaptor_output_fasta | \
  python3 $fcs_gx clean genome \
  --action-report $fcs_gx_report \
  --output $final_output_fasta \
  --contam-fasta-out $final_output_contam_fasta
