### ISSUE TITLE
[BUG]: v0.4.0 fcs.py help is broken

### ISSUE THREAD

**Issue by ptrebert** [ncbi/fcs#48]
*Describe the bug*
Displaying the command line help of the `fcs.py` script only leads to errors.

```
Traceback (most recent call last):
  File "fcs.py", line 480, in <module>
    sys.exit(main())
  File "fcs.py", line 469, in main
    gx.run()
  File "fcs.py", line 386, in run
    self.args.func(self)
  File "fcs.py", line 364, in run_screen_mode
    self.run_gx()
  File "fcs.py", line 235, in run_gx
    self.safe_exec(docker_args)
  File "fcs.py", line 150, in safe_exec
    subprocess.run(args, shell=False, check=True, text=True, stdout=sys.stdout, stderr=sys.stderr)
  File "/gpfs/project/ebertp/software/conda/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/gpfs/project/ebertp/software/conda/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/gpfs/project/ebertp/software/conda/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'docker'
```

*To Reproduce*
`python3 fcs.py screen genome --help`
(copied from wiki, section `D. Screen the genome`)

*Software versions (please complete the following information):*
 - Python 3.8.15

*Additional context*
Adding the gx singularity container `.sif` with the option `--image` changes the error to:
```
$ python3 fcs.py --image fcs-gx.0.4.0.sif screen genome --help

Traceback (most recent call last):
  File "fcs.py", line 480, in <module>
    sys.exit(main())
  File "fcs.py", line 469, in main
    gx.run()
  File "fcs.py", line 386, in run
    self.args.func(self)
  File "fcs.py", line 364, in run_screen_mode
    self.run_gx()
  File "fcs.py", line 235, in run_gx
    self.safe_exec(docker_args)
  File "fcs.py", line 150, in safe_exec
    subprocess.run(args, shell=False, check=True, text=True, stdout=sys.stdout, stderr=sys.stderr)
  File "/gpfs/project/ebertp/software/conda/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/gpfs/project/ebertp/software/conda/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/gpfs/project/ebertp/software/conda/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'singularity'
```

Best,
Peter

**Comment by pstrope** [comment]
Hi Peter, your first command works for me.  For the second, putting the `--image` after` screen genome` works for me:
`python3 fcs.py screen genome --image fcs-gx.sif --help`

Could you please confirm you have singularity installed in your system, and the path to the downloaded sif file is the current working directory?

**Comment by ptrebert** [comment]
Hi pstrope. Thanks for taking a look. I now understand that the help displayed in the above case pertains to the app inside the container, which thus needs to be opened first; maybe, the error of not finding the singularity executable could be made more explicit in the sense that it is required to display the command line help here.

I guess the first version worked for you because you have docker on your system?

After loading the singularity env module on our server, the second version works for me as well, but also as described above with the `--image` option right after `fcs.py`:
```
$ python3 fcs.py --image fcs-gx.0.4.0.sif screen genome --help
# prints help
```
