### ISSUE TITLE
[BUG]: <title>Download database failed, please help me to see what went wrong, thank you.

### ISSUE THREAD

**Issue by zhaoxuetong** [ncbi/fcs#76]
[jiayk@fatltd2 zhaoxt]$ python3 fcs.py db get --mft "https://ftp.ncbi.nlm.nih.gov/genomes/TOOLS/FCS/database/latest/all.manifest" --dir  "/xtdisk/baoym_gr                                              oup/jiayk/zhaoxt//gxdb"
===============================================================================
Cannot open https://ftp.ncbi.nlm.nih.gov/genomes/TOOLS/FCS/database/latest/all.manifest
Traceback (most recent call last):
  File "/usr/lib/python3.9/urllib/request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.9/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/lib/python3.9/http/client.py", line 950, in send
    self.connect()
  File "/usr/lib/python3.9/http/client.py", line 1417, in connect
    super().connect()
  File "/usr/lib/python3.9/http/client.py", line 921, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.9/socket.py", line 822, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_5a6zqj9o/runfiles/cgr_fcs/apps/fcs_genome/public/sync_files/sync_files.py", line 724, in <module>
    main()
  File "/tmp/Bazel.runfiles_5a6zqj9o/runfiles/cgr_fcs/apps/fcs_genome/public/sync_files/sync_files.py", line 621, in main
    src_mft       = get_mft(args.mft)
  File "/tmp/Bazel.runfiles_5a6zqj9o/runfiles/cgr_fcs/apps/fcs_genome/public/sync_files/sync_files.py", line 281, in get_mft
    content = get_content(url)
  File "/tmp/Bazel.runfiles_5a6zqj9o/runfiles/cgr_fcs/apps/fcs_genome/public/sync_files/sync_files.py", line 129, in get_content
    else get_content_from_ordinary_url(url_str) if "://" in url_str
  File "/tmp/Bazel.runfiles_5a6zqj9o/runfiles/cgr_fcs/apps/fcs_genome/public/sync_files/sync_files.py", line 117, in get_content_from_ordinary_url
    with urllib.request.urlopen(url, timeout=10, context=ctx) as r:
  File "/usr/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/usr/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.9/urllib/request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>
Traceback (most recent call last):
  File "fcs.py", line 445, in <module>
    sys.exit(main())
  File "fcs.py", line 434, in main
    gx.run()
  File "fcs.py", line 345, in run
    self.args.func(self)
  File "fcs.py", line 335, in run_db_mode
    self.run_sync_files()
  File "fcs.py", line 208, in run_sync_files
    self.safe_exec(sync_files_args)
  File "fcs.py", line 166, in safe_exec
    subprocess.run(args, shell=False, check=True, stdout=sys.stdout, stderr=sys.stderr)
  File "/usr/lib64/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['docker', 'run', '-it', '--rm', '-v', '/xtdisk/baoym_group/jiayk/zhaoxt/gxdb:/app/db/gxdb/', 'ncbi/fcs-gx:latest'                                              , 'python3', '/app/bin/sync_files', 'get', '--mft', 'https://ftp.ncbi.nlm.nih.gov/genomes/TOOLS/FCS/database/latest/all.manifest', '--dir', '/app/db/gxdb/                                              ']' returned non-zero exit status 1.

**Comment by zhaoxuetong** [comment]
The network is fine because I can download the data using wget in local.  The same problem applies to test-only database.

**Comment by etvedte** [comment]
I can't reproduce this error running Docker on a Google Cloud host. Searching for similar error messages suggests this is a DNS lookup issue.

I would suggest you download the database files from https://ftp.ncbi.nlm.nih.gov/genomes/TOOLS/FCS/database/latest/ using your preferred method. If it is possible, you should try running `fcs.py db check` to see if the files match the source on NCBI FTP, but you might encounter similar error messages.
