### ISSUE TITLE
subprocess.CalledProcessError 

### ISSUE THREAD

**Issue by zilaijuand** [ncbi/fcs#94]
Hi, developer:
I run fcs-gx with singularity using the following command and meet this error messages. 

python3 fcs_db/fcs.py --image=../fcs/fcs-gx.sif screen genome --fasta ../../genome.fasta --out-dir gx_aris_out --gx-db fcs_db --tax-id 1

Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_oslwp9y_/runfiles/gdh_datasets/apps/fcs_genome/public/run_gx.py", line 1091, in <module>
    main()
  File "/tmp/Bazel.runfiles_oslwp9y_/runfiles/gdh_datasets/apps/fcs_genome/public/run_gx.py", line 1054, in main
    fill_missing_args(args)
  File "/tmp/Bazel.runfiles_oslwp9y_/runfiles/gdh_datasets/apps/fcs_genome/public/run_gx.py", line 550, in fill_missing_args
    assert args.div, "Could not look-up blast-div for the tax-id. Must be specified wih --div"
AssertionError: Could not look-up blast-div for the tax-id. Must be specified wih --div
Traceback (most recent call last):
  File "/public/home/zilaijuan/software/nt_dataset/fcs_db/fcs.py", line 476, in <module>
    sys.exit(main())
  File "/public/home/zilaijuan/software/nt_dataset/fcs_db/fcs.py", line 465, in main
    gx.run()
  File "/public/home/zilaijuan/software/nt_dataset/fcs_db/fcs.py", line 347, in run
    self.args.func(self)
  File "/public/home/zilaijuan/software/nt_dataset/fcs_db/fcs.py", line 325, in run_screen_mode
    self.run_gx()
  File "/public/home/zilaijuan/software/nt_dataset/fcs_db/fcs.py", line 243, in run_gx
    self.safe_exec(docker_args)
  File "/public/home/zilaijuan/software/nt_dataset/fcs_db/fcs.py", line 168, in safe_exec
    subprocess.run(args, shell=False, check=True, text=True, stdout=sys.stdout, stderr=sys.stderr)
  File "/public/home/zilaijuan/anaconda3/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['singularity', 'exec', '--bind', '/public/home/zilaijuan/software/nt_dataset:/app/db/gxdb/', '--bind', '/public/home/zilaijuan/Aristolochia/hifi_and_ont:/sample-volume/', '--bind', '/public/home/zilaijuan/software/nt_dataset/gx_aris_out:/output-volume/', '../fcs/fcs-gx.sif', 'python3', '/app/bin/run_gx', '--fasta', '/sample-volume/finish.fasta', '--out-dir', '/output-volume/', '--gx-db', '/app/db/gxdb/fcs_db', '--tax-id', '1']' returned non-zero exit status 1.

Thanks for your work and the update, looking forward to your help.

**Comment by etvedte** [comment]
`--tax-id 1` should work if you also set `--div unknown`

Eric
